removed sh extension and cleaned up init script also added the UUID, Truck ID, and IP to the call to home

diff --git a/bin/cl-lcr-cli b/bin/cl-lcr-cli
--- a/bin/cl-lcr-cli
+++ b/bin/cl-lcr-cli
@@ -1,40 +1,52 @@
 #!/bin/bash
 
+####
 # Cleveland LCR Daemon - Control Script
 #
 # useage: ./cl-lcr-daemon [start|stop|register|unregister]
 #
 # Created by: Matthew Dunham <matt@hotcoffeydesign.com>
+####
 
-function program_is_installed {
+truckID=$(cat /etc/cl-lcr-truck || echo "new")
+oldUUID=$(cat /etc/cl-lcr-uuid || echo "new")
+UUID=$(mount | grep '^/dev' | grep 'on / ' |  cut -d " " -f 1)
+_IP=$(hostname -I) || "no ip"
+
+if [[ oldUUID = "new" || oldUUID != UUID ]]; then:
+	echo $UUID > /etc/cl-lcr-uuid
+	UUID="$oldUUID->$UUID"
+fi
+
+program_is_installed() {
 	local return_=1
 	type $1 >/dev/null 2>&1 || { local return_=0; }
 	echo "$return_"
 }
 
-function program_is_running {
+program_is_running() {
 	local return_=1
 	pidof $1 >/dev/null 2>&1 || { local return_=0; }
 	echo "$return_"
 }
 
-function npm_package_is_installed {
+npm_package_is_installed() {
 	local return_=1
 	ls node_modules | grep $1 >/dev/null 2>&1 || { local return_=0; }
 	echo "$return_"
 }
 
-function echo_fail {
+echo_fail() {
 	printf "\e[31m✘ ${1}"
 	printf "\033\e[0m"
 }
 
-function echo_pass {
+echo_pass() {
 	printf "\e[32m✔ ${1}"
 	printf "\033\e[0m"
 }
 
-function echo_if {
+echo_if() {
 	if [ $1 == 1 ]; then
 		echo_pass $2
 	else
@@ -78,7 +90,7 @@ case "$1" in
 		echo " - sqlite3  $(echo_if $(npm_package_is_installed sqlite3))"
 		echo "--------------------------"
 		echo -n "Installing init.d script  - "
-		(cp /root/cl-lcr-daemon/bin/cl-lcr-daemon-initd.sh /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
+		(cp /root/cl-lcr-daemon/bin/cl-lcr-daemon /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
 		echo -n "Setting file permissions  - "
 		(chmod 755 /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
 		echo -n "Registering script with update-rc - "
@@ -87,7 +99,7 @@ case "$1" in
 		echo "Registration Complete"
 	;;
 	verify)
-		systemctl is-active --quiet cl-lcr-daemon || (service cl-lcr-daemon start; hologram network connect; hologram send --cloud --devicekey 'ujk{]5pX' 'down?'; hologram network disconnect)
+		systemctl is-active --quiet cl-lcr-daemon || (service cl-lcr-daemon start; hologram send "down:$UUID:$truckID:$_IP")
 		python2 /root/cl-lcr-daemon/bin/gps.py
 	;;
 	unregister)
@@ -105,7 +117,7 @@ case "$1" in
 		echo "Unregister Complete"
 	;;
 	*)
-		echo "Usage: ./cl-lcr-daemon [start|stop|register|unregister]"
+		echo "Usage: ./cl-lcr-cli [start|stop|register|unregister]"
 		exit 1
     ;;
 esac
