cleaned up cli script

diff --git a/bin/cl-lcr-cli b/bin/cl-lcr-cli
--- a/bin/cl-lcr-cli
+++ b/bin/cl-lcr-cli
@@ -28,83 +28,23 @@ fi
 
 payloadStr="$UUID:$truckID:$_IP"
 
-program_is_installed() {
-	local return_=1
-	type $1 >/dev/null 2>&1 || { local return_=0; }
-	echo "$return_"
-}
-
-program_is_running() {
-	local return_=1
-	pidof $1 >/dev/null 2>&1 || { local return_=0; }
-	echo "$return_"
-}
-
-npm_package_is_installed() {
-	local return_=1
-	ls node_modules | grep $1 >/dev/null 2>&1 || { local return_=0; }
-	echo "$return_"
-}
-
-echo_fail() {
-	printf "\e[31m✘ ${1}"
-	printf "\033\e[0m"
-}
-
-echo_pass() {
-	printf "\e[32m✔ ${1}"
-	printf "\033\e[0m"
-}
-
-echo_if() {
-	if [ $1 == 1 ]; then
-		echo_pass $2
-	else
-		echo_fail $2
-	fi
-}
-
 case "$1" in
 	start)
-		echo "--------------------------"
-		echo "-  CL-LCR-Daemon by HCD  -"
-		echo "--------------------------"
-		echo "Verifying Dependencies"
-		echo " - node        $(echo_if $(program_is_installed node))"
-		echo " - bleno       $(echo_if $(npm_package_is_installed bleno))"
-		echo " - serialport  $(echo_if $(npm_package_is_installed serialport))"
-		echo " - sqlite3  $(echo_if $(npm_package_is_installed sqlite3))"
-		echo "--------------------------"
-		echo -n "Starting cl-lcr-daemon - "
 		service cl-lcr-daemon start
-		sleep 2
-		echo "$(echo_if $(program_is_running node))"
-		echo "--------------------------"
-		echo "Daemon Start Complete"
         ;;
 	stop)
-		echo "--------------------------"
-		echo "-  CL-LCR-Daemon by HCD  -"
-		echo "--------------------------"
-		echo -n "Stopping cl-lcr-daemon - "
 		service cl-lcr-daemon stop
-	;;
+		;;
 	register)
 		echo "--------------------------"
 		echo "-  CL-LCR-Daemon by HCD  -"
 		echo "--------------------------"
-		echo "Verifying Dependencies"
-		echo " - node        $(echo_if $(program_is_installed node))"
-		echo " - bleno       $(echo_if $(npm_package_is_installed bleno))"
-		echo " - serialport  $(echo_if $(npm_package_is_installed serialport))"
-		echo " - sqlite3  $(echo_if $(npm_package_is_installed sqlite3))"
-		echo "--------------------------"
 		echo -n "Installing init.d script  - "
-		(cp /root/cl-lcr-daemon/bin/cl-lcr-daemon /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
+		cp /root/cl-lcr-daemon/bin/cl-lcr-daemon /etc/init.d/cl-lcr-daemon || echo " - Unable to install service"
 		echo -n "Setting file permissions  - "
-		(chmod 755 /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
+		chmod 755 /etc/init.d/cl-lcr-daemon || echo "Failed to set permissions"
 		echo -n "Registering script with update-rc - "
-		(update-rc.d cl-lcr-daemon defaults && echo "$(echo_pass)") || echo "$(echo_fail)"
+		update-rc.d cl-lcr-daemon defaults || echo "Failed to update rc"
 		echo "--------------------------"
 		echo "Registration Complete"
 	;;
@@ -119,11 +59,11 @@ case "$1" in
 		echo -n "Stopping the daemon - "
 		killall node &> /dev/null
 		killall cl-lcr-daemon &> /dev/null
-		echo "$(echo_pass)"
+		service cl-lcr-daemon stop
 		echo -n "Removing from update-rc.d - "
-		(update-rc.d -f cl-lcr-daemon remove && echo "$(echo_pass)") || echo "$(echo_fail)"
+		update-rc.d -f cl-lcr-daemon remove || echo "Failed to remove from update-rc"
 		echo -n "Removing init.d script    - "
-		(rm -f /etc/init.d/cl-lcr-daemon && echo "$(echo_pass)") || echo "$(echo_fail)"
+		rm -f /etc/init.d/cl-lcr-daemon || echo "Unable to remove service file"
 		echo "Unregister Complete"
 	;;
 	*)
