fixed the call to home

diff --git a/bin/cl-lcr-daemon b/bin/cl-lcr-daemon
--- a/bin/cl-lcr-daemon
+++ b/bin/cl-lcr-daemon
@@ -18,80 +18,104 @@ pid_file="/var/run/$name.pid"
 stdout_log="/var/log/$name.log"
 stderr_log="/var/log/$name.err"
 
+if [ ! -f /etc/cl-lcr-truck ]; then
+	echo "new" > /etc/cl-lcr-truck
+fi
+
+if [ ! -f /etc/cl-lcr-uuid ]; then
+	echo "new" > /etc/cl-lcr-uuid
+fi
+
+truckID=$(cat /etc/cl-lcr-truck)
+oldUUID=$(cat /etc/cl-lcr-uuid)
+UUID=$(mount | grep '^/dev' | grep 'on / ' |  cut -d " " -f 1)
+_IP=$(hostname -I) || "no ip"
+
+if [[ oldUUID = "new" || oldUUID != UUID ]]; then:
+	echo $UUID > /etc/cl-lcr-uuid
+	UUID="$oldUUID->$UUID"
+fi
+
+payloadStr="$UUID:$truckID:$_IP"
+
 get_pid() {
-    cat "$pid_file"
+	cat "$pid_file"
 }
 
 is_running() {
-    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
+	[ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
 }
 
 case "$1" in
-    start)
-    if is_running; then
-        echo "Already started"
-    else
-		echo "Starting $name"
-		cd "$dir"
-		$cmd >> "$stdout_log" 2>> "$stderr_log" &
-		echo $! > "$pid_file"
-		if ! is_running; then
-			echo "Unable to start, see $stdout_log and $stderr_log"
-			exit 1
-		else:
-			echo "Started successfully logging output to $stdout_log and $stderr_log"
+	start)
+		if is_running; then
+			echo "Already started"
+		else
+			echo "Starting $name"
+			cd "$dir"
+			./bin/boot >/dev/null 2>&1
+			$cmd >> "$stdout_log" 2>> "$stderr_log" &
+			echo $! > "$pid_file"
+			if ! is_running; then
+				echo "Unable to start, see $stdout_log and $stderr_log"
+				exit 1
+			else:
+				echo "Started successfully logging output to $stdout_log and $stderr_log"
+			fi
 		fi
-    fi
-    ;;
-    stop)
-    if is_running; then
-        echo -n "Stopping $name.."
-        kill `get_pid`
-        for i in 1 2 3 4 5 6 7 8 9 10
-        # for i in `seq 10`
-        do
-            if ! is_running; then
-                break
-            fi
+		;;
+	stop)
+		if is_running; then
+			echo -n "Stopping $name.."
+			kill `get_pid`
+			for i in 1 2 3 4 5 6 7 8 9 10
+			do
+				if ! is_running; then
+					break
+				fi
 
-            echo -n "."
-            sleep 1
-        done
-        echo
+				echo -n "."
+				sleep 1
+			done
+			echo
 
-        if is_running; then
-            echo "Not stopped; may still be shutting down or shutdown may have failed"
-            exit 1
-        else
-            echo "Stopped"
-            if [ -f "$pid_file" ]; then
-                rm "$pid_file"
-            fi
-        fi
-    else
-        echo "Not running"
-    fi
-    ;;
-    restart)
-    $0 stop
-    if is_running; then
-        echo "Unable to stop, will not attempt to start"
-        exit 1
-    fi
-    $0 start
-    ;;
-    status)
-    if is_running; then
-        echo "Running"
-    else
-        echo "Stopped"
-        exit 1
-    fi
-    ;;
-    *)
-    echo "Usage: $0 {start|stop|restart|status}"
-    exit 1
-    ;;
+			if is_running; then
+				echo "Not stopped; may still be shutting down or shutdown may have failed"
+				hologram send "stop_fail:$payloadStr"
+				exit 1
+			else
+				echo "Stopped"
+				if [ -f "$pid_file" ]; then
+					rm "$pid_file"
+				fi
+				hologram send "stopped:$payloadStr"
+			fi
+		else
+			echo "Not running"
+		fi
+		;;
+	restart)
+		$0 stop
+		sleep 1
+		if is_running; then
+			echo "Unable to stop, will not attempt to start"
+			hologram send "stop_fail:$payloadStr"
+			exit 1
+		fi
+		$0 start
+		;;
+	status)
+		if is_running; then
+			echo "Running"
+		else
+			echo "Stopped"
+			exit 1
+		fi
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart|status}"
+		exit 1
+		;;
 esac
 
 exit 0
